name: 'Sync Lockfile'
description: 'Auto-sync package-lock.json when package.json changes'

inputs:
  token:
    description: 'GitHub token with push permissions (PAT recommended for Dependabot PRs)'
    required: true
  working-directory:
    description: 'Directory containing package.json'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Check if lockfile needs update
      id: check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if npm ci 2>/dev/null; then
          echo "needs_update=false" >> $GITHUB_OUTPUT
          echo "Lockfile is already in sync"
        else
          echo "needs_update=true" >> $GITHUB_OUTPUT
          echo "Lockfile needs regeneration"
        fi

    - name: Regenerate lockfile
      if: steps.check.outputs.needs_update == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        rm -f package-lock.json
        npm install --package-lock-only --ignore-scripts
        echo "package-lock.json regenerated"

    - name: Commit updated lockfile
      if: steps.check.outputs.needs_update == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: sync package-lock.json"
        file_pattern: "${{ inputs.working-directory }}/package-lock.json"
