name: 'GitVersion'
description: 'Calculate semantic version using GitVersion'

inputs:
  config-file:
    description: 'Path to GitVersion config file'
    required: false
    default: 'GitVersion.yml'

outputs:
  version:
    description: 'Full semantic version (e.g., 1.2.3)'
    value: ${{ steps.gitversion.outputs.semVer }}
  major:
    description: 'Major version number'
    value: ${{ steps.gitversion.outputs.major }}
  minor:
    description: 'Minor version number'
    value: ${{ steps.gitversion.outputs.minor }}
  patch:
    description: 'Patch version number'
    value: ${{ steps.gitversion.outputs.patch }}
  prerelease:
    description: 'Pre-release tag'
    value: ${{ steps.gitversion.outputs.preReleaseTag }}
  branch:
    description: 'Branch name'
    value: ${{ steps.gitversion.outputs.branchName }}
  sha:
    description: 'Commit SHA'
    value: ${{ steps.gitversion.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.x'

    - name: Calculate version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        useConfigFile: true
        configFilePath: ${{ inputs.config-file }}

    - name: Summary
      shell: bash
      run: |
        echo "Version: ${{ steps.gitversion.outputs.semVer }}"
