name: 'Setup Node.js'
description: 'Setup Node.js with npm token for private registry'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  npm-token:
    description: 'NPM token for private registry (set as NPM_GITHUB_TOKEN env var)'
    required: false

outputs:
  node-version:
    description: 'Installed Node.js version'
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set NPM_GITHUB_TOKEN environment variable
      if: inputs.npm-token != ''
      shell: bash
      run: echo "NPM_GITHUB_TOKEN=${{ inputs.npm-token }}" >> $GITHUB_ENV
